"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import * as THREE from "three";
import {OrbitControls} from "three/examples/jsm/controls/OrbitControls.js";
import * as satellite from "satellite.js";
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000/api/v1";
type Point={id:string;kind:string;label?:string;lat?:number;lon?:number;source?:string;magnitude?:number;altitude_m?:number;heading?:number;confidence?:number;tle_line1?:string;tle_line2?:string;[k:string]:any};
type Layers={updated_at:number;layers:Record<string,Point[]>;capabilities?:Record<string,boolean>;sources:any[];disclaimer:string};
function api(path:string,token:string){return fetch(API+path,{headers:{Authorization:`Bearer ${token}`}}).then(async r=>{const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||`HTTP ${r.status}`);return d})}
function ll(lat:number,lon:number,r=3){const p=THREE.MathUtils.degToRad(lat),q=THREE.MathUtils.degToRad(lon);return new THREE.Vector3(r*Math.cos(p)*Math.cos(q),r*Math.sin(p),-r*Math.cos(p)*Math.sin(q))}
export default function Spatial(){
 const mount=useRef<HTMLDivElement>(null),draw=useRef<HTMLCanvasElement>(null),sceneRef=useRef<any>(null);
 const [layers,setLayers]=useState<Layers|null>(null),[casePoints,setCasePoints]=useState<Point[]>([]),[selected,setSelected]=useState<Point|null>(null),[style,setStyle]=useState("standard"),[error,setError]=useState(""),[contextData,setContextData]=useState<any>(null),[showSources,setShowSources]=useState(false);
 const [on,setOn]=useState<Record<string,boolean>>({earthquakes:true,aircraft:true,satellites:true,launches:true,radio:false,natural_events:true,news_events:true,evidence:true,vessels:false,traffic:false,cctv:false,fires:false});
 const [hud,setHud]=useState(true),[detect,setDetect]=useState(true),[cockpit,setCockpit]=useState(false),[tour,setTour]=useState(false),[drawMode,setDrawMode]=useState(false),[satLive,setSatLive]=useState(true);
 const token=typeof window!=="undefined"?localStorage.getItem("nexus_token")||"":"";
 const caseId=useMemo(()=>new URLSearchParams(typeof window!=="undefined"?location.search:"").get("case")||"",[]);
 useEffect(()=>{if(!token){setError("Sign in to use Spatial Intelligence.");return}Promise.all([api("/v3/spatial/layers",token),caseId?api(`/v3/spatial/cases/${caseId}/points`,token):Promise.resolve({points:[]})]).then(([a,b])=>{setLayers(a);setCasePoints(b.points||[])}).catch(e=>setError(e.message))},[caseId,token]);
 useEffect(()=>{if(!mount.current)return;const scene=new THREE.Scene();scene.background=new THREE.Color(0x02060b);const camera=new THREE.PerspectiveCamera(45,1,.1,100);camera.position.set(0,1.4,7);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(mount.current.clientWidth,mount.current.clientHeight);mount.current.appendChild(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=4;controls.maxDistance=12;scene.add(new THREE.Mesh(new THREE.SphereGeometry(3,64,64),new THREE.MeshBasicMaterial({color:0x0b2030,wireframe:true,transparent:true,opacity:.58})));scene.add(new THREE.Mesh(new THREE.SphereGeometry(3.08,48,48),new THREE.MeshBasicMaterial({color:0x1595bd,transparent:true,opacity:.08,side:THREE.BackSide})));const grid=new THREE.Group();for(let lat=-60;lat<=60;lat+=30){const pts=[];for(let lon=-180;lon<=180;lon+=4)pts.push(ll(lat,lon,3.01));grid.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:0x16475c,transparent:true,opacity:.35})))}for(let lon=-180;lon<180;lon+=30){const pts=[];for(let lat=-90;lat<=90;lat+=4)pts.push(ll(lat,lon,3.01));grid.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:0x16475c,transparent:true,opacity:.35})))}scene.add(grid);scene.add(new THREE.AmbientLight(0xffffff,1));const resize=()=>{if(!mount.current)return;camera.aspect=mount.current.clientWidth/mount.current.clientHeight;camera.updateProjectionMatrix();renderer.setSize(mount.current.clientWidth,mount.current.clientHeight)};addEventListener("resize",resize);let raf=0;const loop=()=>{controls.update();renderer.render(scene,camera);raf=requestAnimationFrame(loop)};loop();sceneRef.current={scene,camera,renderer,controls,markers:[],satelliteMarkers:[]};return()=>{cancelAnimationFrame(raf);removeEventListener("resize",resize);renderer.dispose();mount.current?.removeChild(renderer.domElement);sceneRef.current=null}},[]);
 useEffect(()=>{const s=sceneRef.current;if(!s||!layers)return;s.markers.forEach((m:any)=>s.scene.remove(m));s.markers=[];const data=Object.keys(on).filter(k=>on[k]).flatMap(k=>k==="evidence"?casePoints:layers.layers[k]||[]);for(const p of data){if(typeof p.lat!=="number"||typeof p.lon!=="number")continue;const color=p.kind==="earthquake"?0xffa33b:p.kind==="aircraft"?0x55e7ff:p.kind==="satellite"?0xb58cff:p.kind==="launch"?0xff6b6b:p.kind==="radio"?0x4cff9b:p.kind==="natural_event"?0xff7a45:p.kind==="news_event"?0xffd45c:0xb56cff;const mesh=new THREE.Mesh(new THREE.SphereGeometry(p.kind==="earthquake"?Math.max(.035,Math.min(.13,(p.magnitude||1)*.025)):.045,10,10),new THREE.MeshBasicMaterial({color}));mesh.position.copy(ll(p.lat,p.lon,3.08));mesh.userData=p;s.scene.add(mesh);s.markers.push(mesh)}},[layers,casePoints,on]);
 useEffect(()=>{const s=sceneRef.current;const sats=(layers?.layers?.satellites||[]).filter(p=>p.tle_line1&&p.tle_line2);if(!s||!sats.length||!on.satellites||!satLive)return;let stopped=false;const update=()=>{if(stopped)return;s.satelliteMarkers.forEach((m:any)=>s.scene.remove(m));s.satelliteMarkers=[];const now=new Date();for(const p of sats){try{const satrec=satellite.twoline2satrec(p.tle_line1!,p.tle_line2!);const pv:any=satellite.propagate(satrec,now);if(!pv.position||typeof pv.position!=="object")continue;const gmst=satellite.gstime(now);const geo=satellite.eciToGeodetic(pv.position,gmst);const lat=satellite.degreesLat(geo.latitude);const lon=satellite.degreesLong(geo.longitude);const altitude=geo.height*1000;if(!Number.isFinite(lat)||!Number.isFinite(lon))continue;const marker=new THREE.Mesh(new THREE.SphereGeometry(.065,8,8),new THREE.MeshBasicMaterial({color:0xb58cff}));marker.position.copy(ll(lat,lon,3.11));marker.userData={...p,lat,lon,altitude_m:altitude,derived:true,source:"CelesTrak TLE / SGP4"};s.scene.add(marker);s.satelliteMarkers.push(marker)}catch{continue}}};update();const timer=setInterval(update,2000);return()=>{stopped=true;clearInterval(timer);s.satelliteMarkers.forEach((m:any)=>s.scene.remove(m));s.satelliteMarkers=[]}},[layers,on.satellites,satLive]);
 useEffect(()=>{if(!draw.current)return;const c=draw.current,x=c.getContext("2d");if(!x)return;const resize=()=>{c.width=c.clientWidth*devicePixelRatio;c.height=c.clientHeight*devicePixelRatio;x.scale(devicePixelRatio,devicePixelRatio)};resize();addEventListener("resize",resize);let drawing=false;x.strokeStyle="#66e6ff";x.lineWidth=2;c.onpointerdown=e=>{if(!drawMode)return;drawing=true;x.beginPath();x.moveTo(e.offsetX,e.offsetY)};c.onpointermove=e=>{if(drawing){x.lineTo(e.offsetX,e.offsetY);x.stroke()}};c.onpointerup=()=>drawing=false;return()=>{removeEventListener("resize",resize);c.onpointerdown=null;c.onpointermove=null;c.onpointerup=null}},[drawMode]);
 useEffect(()=>{if(!tour)return;const timer=setInterval(()=>{const s=sceneRef.current;if(s)s.camera.position.applyAxisAngle(new THREE.Vector3(0,1,0),.015)},50);return()=>clearInterval(timer)},[tour]);
 async function focus(p:Point){const s=sceneRef.current;if(!s||typeof p.lat!=="number"||typeof p.lon!=="number")return;setSelected(p);s.camera.position.copy(ll(p.lat,p.lon,1).normalize().multiplyScalar(cockpit?3.7:6));s.controls.target.set(0,0,0);try{setContextData(await api(`/v3/spatial/context?lat=${p.lat}&lon=${p.lon}&radius_m=3000`,token))}catch(e:any){setError(e.message)}}
 function share(){const q=new URLSearchParams();if(caseId)q.set("case",caseId);q.set("style",style);q.set("hud",String(hud));navigator.clipboard?.writeText(`${location.origin}${location.pathname}?${q}`)}
 const visible=Object.keys(on).filter(k=>on[k]).flatMap(k=>k==="evidence"?casePoints:layers?.layers[k]||[]);const styleFilter=style==="nvg"?"sepia(.5) hue-rotate(55deg) saturate(1.5)":style==="flir"?"sepia(1) hue-rotate(325deg) saturate(2)":style==="noir"?"grayscale(1) contrast(1.3)":style==="snow"?"brightness(1.35) grayscale(.5)":"none";
 const layerNames:[[string,string],...Array<[string,string]>]=[["earthquakes","Earthquakes"],["aircraft","Aircraft"],["satellites","Satellites"],["launches","Space launches"],["radio","Radio"],["natural_events","NASA natural events"],["news_events","GDELT news events"],["evidence","Case evidence"],["vessels","Vessels"],["traffic","Traffic"],["cctv","Public cameras"],["fires","Fires"]];
 return <main style={{height:"100vh",background:"#02060b",color:"#dceeff",fontFamily:"Inter,system-ui",overflow:"hidden"}}><header style={{height:56,display:"flex",alignItems:"center",justifyContent:"space-between",padding:"0 16px",borderBottom:"1px solid #183246",background:"#06101a"}}><div><b style={{letterSpacing:2}}>NEXUS<span style={{color:"#49ddff"}}>OSINT</span></b><span style={{marginLeft:14,color:"#6e8599",fontSize:12}}>SPATIAL INTELLIGENCE / PUBLIC SIGNALS</span></div><div style={{display:"flex",gap:6,flexWrap:"wrap",justifyContent:"end"}}>{["standard","nvg","flir","noir","snow"].map(x=><button key={x} onClick={()=>setStyle(x)} style={{background:style===x?"#12445a":"#091722",color:"#bcecff",border:"1px solid #1b4054",borderRadius:6,padding:"6px 8px",fontSize:10}}>{x}</button>)}<button onClick={share}>Share</button><button onClick={()=>setHud(!hud)}>HUD</button><button onClick={()=>setDetect(!detect)}>Detect</button></div></header>
 <div style={{display:"grid",gridTemplateColumns:"250px 1fr 310px",height:"calc(100vh - 56px)"}}><aside style={{borderRight:"1px solid #183246",padding:12,background:"#050d15",overflow:"auto"}}><h3>LIVE LAYERS</h3>{layerNames.map(([id,label])=><label key={id} style={{display:"flex",justifyContent:"space-between",padding:"8px 4px",fontSize:11}}><span><input type="checkbox" checked={!!on[id]} onChange={e=>setOn({...on,[id]:e.target.checked})}/> {label}</span><small>{id==="evidence"?casePoints.length:layers?.layers[id]?.length||0}</small></label>)}<h3 style={{marginTop:18}}>TOOLS</h3><button onClick={()=>setSatLive(!satLive)} style={{width:"100%",padding:8}}>{satLive?"Pause Satellite Propagation":"Resume Satellite Propagation"}</button><button onClick={()=>setCockpit(!cockpit)} style={{width:"100%",padding:8,marginTop:6}}>{cockpit?"Exit Cockpit":"Cockpit View"}</button><button onClick={()=>setDrawMode(!drawMode)} style={{width:"100%",padding:8,marginTop:6}}>{drawMode?"Stop Whiteboard":"Voice/Whiteboard"}</button><button onClick={()=>setTour(!tour)} style={{width:"100%",padding:8,marginTop:6}}>{tour?"Stop Scene Director":"Scene Director"}</button><button onClick={()=>setShowSources(!showSources)} style={{width:"100%",padding:8,marginTop:6}}>Public Source Registry</button><button onClick={()=>sceneRef.current?.controls.reset()} style={{width:"100%",padding:8,marginTop:6}}>Reset Globe</button>{showSources&&<div style={{marginTop:10,fontSize:9,color:"#8aa4b8"}}>{(layers?.sources||[]).map((s:any,i:number)=><div key={s.id||i} style={{padding:"6px 0",borderBottom:"1px solid #13293a"}}><b>{s.name}</b><br/>{s.kind||"public signal"} · {s.status||s.access||"public"}</div>)}</div>}<p style={{fontSize:10,color:"#668096",lineHeight:1.5}}>Public-source only. Satellite positions are propagated from public TLEs with SGP4 and are analytical estimates, not direct sensor observations.</p>{error&&<div style={{color:"#ff9aa8",fontSize:11}}>{error}</div>}</aside>
 <section style={{position:"relative",overflow:"hidden"}}><div ref={mount} style={{position:"absolute",inset:0,filter:styleFilter}}/><canvas ref={draw} style={{position:"absolute",inset:0,width:"100%",height:"100%",pointerEvents:drawMode?"auto":"none"}}/>{hud&&<div style={{position:"absolute",inset:12,pointerEvents:"none",border:"1px solid #2ccde644",borderRadius:12}}><div style={{position:"absolute",left:14,top:12,fontSize:10,color:"#6cecff"}}>NEXUS TACTICAL HUD · PUBLIC SIGNAL MODE</div><div style={{position:"absolute",right:14,top:12,fontSize:10,color:"#6cecff"}}>{visible.length} SIGNALS · SGP4 {satLive?"LIVE":"PAUSED"}</div><div style={{position:"absolute",left:14,bottom:12,fontSize:10,color:"#6cecff"}}>STYLE {style.toUpperCase()} · {cockpit?"COCKPIT":"ORBIT"} · {tour?"DIRECTOR":"MANUAL"}</div></div>}{detect&&visible.filter(p=>typeof p.lat==="number").slice(0,30).map((p,i)=><div key={i} style={{position:"absolute",left:`${((p.lon!+180)/360)*100}%`,top:`${((90-p.lat!)/180)*100}%`,border:"1px solid #66e6ff",padding:"2px 4px",fontSize:8,color:"#8eeeff",pointerEvents:"none"}}>{p.kind.toUpperCase()} #{i+1}</div>)}<div style={{position:"absolute",left:14,top:14,padding:"7px 9px",background:"#06111bdd",border:"1px solid #17384b",borderRadius:7,fontSize:10}}>GLOBAL CONTEXT · {layers?new Date(layers.updated_at*1000).toLocaleTimeString():"—"}</div></section>
 <aside style={{borderLeft:"1px solid #183246",padding:12,background:"#050d15",overflow:"auto"}}><h3>PUBLIC SIGNALS</h3>{visible.slice(0,100).map((p,i)=><button key={`${p.id}-${i}`} onClick={()=>focus(p)} style={{width:"100%",textAlign:"left",padding:8,marginBottom:5,background:selected?.id===p.id?"#102b3b":"#07121c",color:"#cbe8f5",border:"1px solid #163447",borderRadius:7}}><b style={{fontSize:10}}>{p.label||p.id}</b><small style={{display:"block",color:"#6d899b",marginTop:2}}>{p.kind} · {p.lat!=null?`${p.lat.toFixed(2)}, ${p.lon?.toFixed(2)}`:"catalog"} · {p.source}</small></button>)}{selected&&<div style={{marginTop:12,padding:9,border:"1px solid #21485d",borderRadius:8,fontSize:10}}><b>SELECTED SIGNAL CONTEXT</b><pre style={{whiteSpace:"pre-wrap",color:"#83dfff",fontSize:9}}>{JSON.stringify({signal:selected,context:contextData},null,2)}</pre></div>}<div style={{marginTop:14,color:"#587286",fontSize:9,lineHeight:1.5}}>{layers?.disclaimer}</div></aside></div></main>
}
