"use client";
import {useEffect,useState} from "react";
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000/api/v1";
type Case={id:string,name:string,description:string,status:string,workflow:string,tags:string[],targets:string[],evidence:any[],notes:any[]};
async function api(path:string,token:string,options:RequestInit={}){const r=await fetch(API+path,{...options,headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`,...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||`HTTP ${r.status}`);return d}
export default function Home(){
 const [token,setToken]=useState("");const [user,setUser]=useState<any>(null);const [login,setLogin]=useState(true);const [username,setUsername]=useState("");const [password,setPassword]=useState("");const [cases,setCases]=useState<Case[]>([]);const [selected,setSelected]=useState<Case|null>(null);const [name,setName]=useState("New Investigation");const [target,setTarget]=useState("");const [tab,setTab]=useState("overview");const [jobs,setJobs]=useState<any[]>([]);const [intel,setIntel]=useState<any>(null);const [audit,setAudit]=useState<any[]>([]);const [entities,setEntities]=useState<any[]>([]);const [meta,setMeta]=useState<any>(null);const [tags,setTags]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 useEffect(()=>{const t=localStorage.getItem("nexus_token");if(t){setToken(t);api("/auth/me",t).then(x=>{setUser(x.user);loadCases(t)}).catch(()=>localStorage.removeItem("nexus_token"))}},[]);
 async function loadCases(t=token){try{const c=await api("/cases/",t);setCases(c);setSelected(s=>s&&c.find((x:Case)=>x.id===s.id)||c[0]||null)}catch(e:any){setError(e.message)}}
 async function auth(){setBusy(true);setError("");try{const d=await api(`/auth/${login?"login":"register"}`,"",{method:"POST",body:JSON.stringify({username,password})});setToken(d.token);setUser(d.user);localStorage.setItem("nexus_token",d.token);await loadCases(d.token)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function createCase(){try{const c=await api("/cases/",token,{method:"POST",body:JSON.stringify({name,description:"Authorized public-source OSINT investigation"})});setCases(x=>[c,...x]);setSelected(c)}catch(e:any){setError(e.message)}}
 async function addTarget(){if(!selected||!target.trim())return;try{const c=await api(`/cases/${selected.id}/targets`,token,{method:"POST",body:JSON.stringify({target:target.trim()})});setSelected(c);setCases(x=>x.map(v=>v.id===c.id?c:v))}catch(e:any){setError(e.message)}}
 async function scan(){if(!selected||!target.trim())return;setBusy(true);try{await api("/platform/jobs",token,{method:"POST",body:JSON.stringify({case_id:selected.id,target:target.trim(),target_type:target.includes("@")==true?"email":target.startsWith("http")?"url":/^([0-9]{1,3}\.){3}[0-9]{1,3}$/.test(target)?"ip":"domain",authorized:true})});await addTarget();setTab("jobs");await pollJobs()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function pollJobs(){try{const d=await api("/platform/jobs",token);setJobs(d.jobs)}catch(e:any){setError(e.message)}}
 async function loadTab(t:string){setTab(t);if(!selected)return;try{if(t==="audit")setAudit((await api("/platform/audit",token)).events);if(t==="jobs")await pollJobs();if(t==="intel"&&target)setIntel(await api("/intelligence/dns-rdap",token,{method:"POST",body:JSON.stringify({domain:target})}));if(t==="entities")setEntities((await api(`/entities/case/${selected.id}`,token)).entities||[]);if(t==="workflow")setMeta(await api(`/workflow/${selected.id}/meta`,token))}catch(e:any){setError(e.message)}}
 async function saveMeta(){if(!selected)return;try{const m=await api(`/workflow/${selected.id}/meta`,token,{method:"PATCH",body:JSON.stringify({tags:tags.split(","),workflow:meta?.workflow,status:meta?.status})});setMeta(m);await loadCases()}catch(e:any){setError(e.message)}}
 async function closeCase(){if(!selected)return;try{const c=await api(`/cases/${selected.id}/close`,token,{method:"POST"});setSelected(c);await loadCases()}catch(e:any){setError(e.message)}}
 if(!user)return <div className="auth"><div className="authbox"><div className="brand">NEXUS<span>OSINT</span></div><p>Public-source investigation workspace</p><input placeholder="Username" value={username} onChange={e=>setUsername(e.target.value)}/><input placeholder="Password (10+ chars)" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><button onClick={auth} disabled={busy}>{busy?"Working…":login?"Sign in":"Create account"}</button><button className="ghost" onClick={()=>setLogin(!login)}>{login?"Need an account? Register":"Already have an account? Sign in"}</button>{error&&<div className="error">{error}</div>}</div></div>;
 const nav=["overview","evidence","entities","jobs","graph","timeline","score","reports","audit","intel","workflow"];
 return <main><header><div className="brand">NEXUS<span>OSINT</span></div><div className="identity">{user.username} · <b>{user.role}</b><button className="ghost" onClick={()=>{localStorage.removeItem("nexus_token");location.reload()}}>Sign out</button></div></header><div className="shell"><aside><button className="new" onClick={createCase}>＋ New Case</button>{cases.map(c=><button key={c.id} className={selected?.id===c.id?"case active":"case"} onClick={()=>setSelected(c)}><b>{c.name}</b><small>{c.workflow} · {c.targets?.length||0} targets</small></button>)}</aside><section className="workspace"><div className="title"><div><h1>{selected?.name||"Investigation Workspace"}</h1><p>{selected?.description||"Create a case to begin."}</p></div><div className="targetbar"><input placeholder="domain / IP / URL / email" value={target} onChange={e=>setTarget(e.target.value)}/><button onClick={addTarget}>Add</button><button onClick={scan} disabled={busy||user.role==="viewer"}>Scan</button></div></div><nav>{nav.map(n=><button key={n} className={tab===n?"selected":""} onClick={()=>loadTab(n)}>{n}</button>)}</nav>{error&&<div className="error">{error}</div>}<div className="grid">
 {tab==="overview"&&<><Card title="Targets"><div className="metric">{selected?.targets?.length||0}</div></Card><Card title="Evidence"><div className="metric">{selected?.evidence?.length||0}</div></Card><Card title="Jobs"><div className="metric">{jobs.length}</div></Card><Card title="Workflow"><div className="metric">{selected?.workflow||"—"}</div></Card><Panel title="Investigation controls"><p>Collect only public-source or explicitly authorized information. Use the target bar for bounded collection and inspect evidence provenance before reporting.</p><button onClick={closeCase} disabled={user.role==="viewer"||selected?.status==="closed"}>Close case</button></Panel></>}
 {tab==="evidence"&&<Panel title="Immutable evidence records"><Table rows={selected?.evidence||[]} cols={["source","target","observed_at","confidence","provenance_hash"]}/></Panel>}
 {tab==="entities"&&<Panel title="Case entity index"><Table rows={entities} cols={["id","entity_type","canonical","fingerprint","first_seen","last_seen"]}/></Panel>}
 {tab==="jobs"&&<Panel title="Persistent background jobs"><Table rows={jobs.filter(j=>!selected||j.case_id===selected.id)} cols={["id","target","target_type","status","attempts","created_at","finished_at"]}/></Panel>}
 {tab==="graph"&&<Panel title="Relationship graph"><div className="graph"><div className="node root">CASE</div>{(selected?.targets||[]).map((t,i)=><div className="node" key={t} style={{left:`${15+(i*17)%75}%`,top:`${20+(i*29)%65}%`}}>{t}</div>)}</div></Panel>}
 {tab==="timeline"&&<Panel title="Evidence timeline"><Table rows={[...(selected?.evidence||[])].sort((a,b)=>String(a.observed_at).localeCompare(String(b.observed_at)))} cols={["observed_at","source","target","confidence"]}/></Panel>}
 {tab==="score"&&<Panel title="Deterministic confidence score"><div className="score">{selected?.evidence?.length?Math.round(selected.evidence.reduce((a:any,e:any)=>a+Number(e.confidence||0),0)/selected.evidence.length*100):0}<small>/100</small></div><p>Explainable evidence confidence; no opaque model score.</p></Panel>}
 {tab==="reports"&&<Panel title="Reports"><p>Deterministic investigation exports.</p><div className="actions"><button onClick={()=>window.open(`${API}/reports/${selected?.id}.md`)}>Markdown</button><button onClick={()=>window.open(`${API}/reports/${selected?.id}.html`)}>HTML</button><button onClick={()=>window.open(`${API}/platform/cases/${selected?.id}/export.json`)}>JSON</button></div></Panel>}
 {tab==="audit"&&<Panel title="Tamper-evident audit viewer"><Table rows={audit} cols={["created_at","actor","action","resource","event_hash"]}/></Panel>}
 {tab==="intel"&&<Panel title="DNS / RDAP intelligence"><p>Enter a domain above and open this tab.</p>{intel&&<pre>{JSON.stringify(intel,null,2)}</pre>}</Panel>}
 {tab==="workflow"&&<Panel title="Case workflow & tags"><p>State: <select value={meta?.workflow||"triage"} onChange={e=>setMeta({...meta,workflow:e.target.value})}>{["triage","active","review","closed"].map(s=><option key={s}>{s}</option>)}</select></p><input placeholder="tags, comma separated" value={tags||((meta?.tags||[]).join(","))} onChange={e=>setTags(e.target.value)}/><button onClick={saveMeta} disabled={user.role==="viewer"}>Save workflow</button></Panel>}
 </div></section></div></main>}
function Card({title,children}:{title:string,children:any}){return <div className="card"><small>{title}</small>{children}</div>};function Panel({title,children}:{title:string,children:any}){return <div className="panel"><h2>{title}</h2>{children}</div>};function Table({rows,cols}:{rows:any[],cols:string[]}){return <div className="tablewrap"><table><thead><tr>{cols.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{cols.map(c=><td key={c}>{typeof r[c]==="object"?JSON.stringify(r[c]):String(r[c]??"—")}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="muted">No records yet.</p>}</div>}
